### ISSUE TITLE
panic: runtime error: slice bounds out of range [2:1]

### ISSUE THREAD

**Issue by BrightGum** [tbvdm/sigtop#19]
Hello,

I have successfully exported several Signal Desktop instances, but encountered now the following issue with one of them:

```
> ~/go/bin/sigtop export-messages -f text messages
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/tbvdm/sigtop/signal.(*MessageBody).insertMentions(0xc000117ac0)
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/mention.go:100 +0x265
github.com/tbvdm/sigtop/signal.(*Context).messages(0xc000064040, 0x5ee2eb?)
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:265 +0x356
github.com/tbvdm/sigtop/signal.(*Context).allConversationMessages(0xc000064040, 0xc000117d40)
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:139 +0xb5
github.com/tbvdm/sigtop/signal.(*Context).ConversationMessages(0xc0000292e0?, 0xc000258000?, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:111 +0xd1
main.exportConversationMessages(0x50?, 0xc0000200c0?, 0x29?, 0x1, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:161 +0x96
main.exportMessages(0x453f1c?, {0x7fff6e2e05c1?, 0x1a?}, 0xc00004fe30?, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:151 +0x22f
main.cmdExportMessages({0xc0000120c0?, 0xc00003c710?, 0x4418c5?})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:128 +0x6d4
main.main()
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/main.go:62 +0x163
```

Similar with a try to do the export year by year for 2021:
```
> ~/go/bin/sigtop export-messages -f text -s 2018-01-01T00:00:00,2018-12-31T23:59:59 messages-2018
> ~/go/bin/sigtop export-messages -f text -s 2019-01-01T00:00:00,2019-12-31T23:59:59 messages-2019
> ~/go/bin/sigtop export-messages -f text -s 2020-01-01T00:00:00,2020-12-31T23:59:59 messages-2020
> ~/go/bin/sigtop export-messages -f text -s 2021-01-01T00:00:00,2021-12-31T23:59:59 messages-2021
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/tbvdm/sigtop/signal.(*MessageBody).insertMentions(0xc000115a40)
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/mention.go:100 +0x265
github.com/tbvdm/sigtop/signal.(*Context).messages(0xc000064040, 0x5ee552?)
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:265 +0x356
github.com/tbvdm/sigtop/signal.(*Context).conversationMessagesSentBetween(0xc000064040, 0xc000115d40, {0xc000115bb0?, 0x4a8b05?, 0x6f65e0?}, {0xc000115bc8?, 0x4fb446?, 0x6f65e0?})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:218 +0x271
github.com/tbvdm/sigtop/signal.(*Context).ConversationMessages(0xc00014e3c0?, 0xc000126000?, {{0x0, 0xed7804ef0, 0x6f65e0}, {0x3b9ac9ff, 0xed961826f, 0x6f65e0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/signal/message.go:117 +0x19c
main.exportConversationMessages(0x50?, 0xc0000200c0?, 0x29?, 0x1, {{0x0, 0xed7804ef0, 0x6f65e0}, {0x3b9ac9ff, 0xed961826f, 0x6f65e0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:161 +0x96
main.exportMessages(0x453f1c?, {0x7ffe8422e5bc?, 0x1a?}, 0xc00004fe30?, {{0x0, 0xed7804ef0, 0x6f65e0}, {0x3b9ac9ff, 0xed961826f, 0x6f65e0}})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:151 +0x22f
main.cmdExportMessages({0xc000012090?, 0xc00003c710?, 0x4418c5?})
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/cmd_export_messages.go:128 +0x6d4
main.main()
	/home/user/go/pkg/mod/github.com/tbvdm/sigtop@v0.1.1/main.go:62 +0x163
```

A database check returns no error:
`> ~/go/bin/sigtop check
`

Is there a (hidden) verbose or debug mode to see whats going on?

**Comment by tbvdm** [comment]
I've created a test branch that will provide a few diagnostics. Please run the following commands and paste the output of the last command:

```
git clone -b test https://github.com/tbvdm/sigtop.git
cd sigtop
go build
./sigtop msg msg
```

Thanks.

**Comment by BrightGum** [comment]
```
~/git/sigtop/sigtop msg msg
message: 3,1*; 0; 0:1,1
valid: 965, 153

```

**Comment by tbvdm** [comment]
It appears that you have a message with a mention that doesn't "fit" into that message. Very curious.

Could you update the test branch and run sigtop again:

```
git pull
go build
rm -fr msg
./sigtop msg msg
```

This time you will also see the JSON dump of the message. Could you take a look and see if there's anything that seems suspicious? For example, does it have a non-empty `errors` array?

Furthermore, you will also see a line like this:

```
conversation: "Alice", sent: 2023-01-02 12:34:56
```

That's the conversation the message belongs to, and the time it was sent. Using that information, could you look up the message in Signal Desktop? What does it look like? Does it consist of a single mention, without any other text?

**Comment by BrightGum** [comment]
Hi, 
thanks for the support.
While trying to find the message the computer swapped to a very high load.
Finally i found it in the database by sqlitebrowser, it is incoming with an empty body.
I searched for the message before and after the relevant one and there is no corresponding entry in Signal Desktop.

**Comment by tbvdm** [comment]
Thanks. Could you check two more things?

First, could you look up the message on your phone? Is it visible there? What does it look like?

Second, could you update the test branch and run sigtop again:

```
git pull
go build
rm -fr msg
./sigtop msg msg
```

sigtop will now adjust the mention so that it fits in the message. Could you open the relevant conversation file in the `msg` directory and look up the message? The message text will consist of a single mention. Does the message make sense within the context of the conversation? Does it look like the correct person is being mentioned? Does the message look complete or does it look like something is missing?
