### ISSUE TITLE
cannot decrypt database key: cannot find encryption key

### ISSUE THREAD

**Issue by psykup** [tbvdm/sigtop#52]
Hello,

look like I'm unlucky with your tool and I haven't dev Go so far :\
```bash
❯ sigtop check-database
sigtop: cannot decrypt database key: cannot find encryption key
```

here is my setup:
- Kernel 6.1.105-1
- Manjaro up to [2024-08-08](https://forum.manjaro.org/t/stable-update-2024-08-08-kernels-nvidia-mesa-amdvlk-firefox-thunderbird-pipewire-wine/166566)
- Signal 7.18.0-1
- Sigtop 0.13.0.r0.g2b9a0f9-1 (from AUR)

content of config.json with a corresponding regex instead of **encryptedKey**:
```json
{
  "mediaPermissions": true,
  "encryptedKey": "/[0-9a-f]{166}/",
  "safeStorageBackend": "kwallet6"
}
```

Thank you very much for your time and efforts

**Comment by psykup** [comment]
OK I found another issue explaining how *The key format for SQLite was changed in latest versions of desktop Signal* ([ Not a database error when running sigtop db #48 ](https://github.com/tbvdm/sigtop/issues/48#issuecomment-2253604742)) and tried the referenced snippet:
```bash
❯ ./signal_get_key.py 
Traceback (most recent call last):
  File "~/.config/Signal/./signal_get_key.py", line 27, in <module>
    assert encrypted_key.startswith(prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
I should have missed something :\

what I did:
1. create a new *signal_get_key.py* file within *Signal* directory,
2. paste the snippet in it,
3. make it executable,
4. adapt *config_file_path* to my environment,
5. change my kwallet password to be sure of its value,
6. put the password in the script,
7. execute it

**Comment by psykup** [comment]
My *encrypted_key* do not start with **b'v10'** but with **b'v11'** so I tried replacing prefix in script:
```bash
❯ ./signal_get_key.py 
Traceback (most recent call last):
  File "~/.config/Signal/./signal_get_key.py", line 32, in <module>
    decrypted_key = unpad(aes_decrypt_cbc(kek, iv, encrypted_key), block_size = 16).decode('ascii')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

Looks like they change at least the padding with a new version but I don't know what to try next

**Comment by psykup** [comment]
[kwallet answer](https://github.com/tbvdm/sigtop/issues/48#issuecomment-2256050015)

Thanks for this great tool :+1:
